search_space:
  batch_size:
    _type: choice
    _value: [ 25, 50, 100, 200 ]
  lr:
    _type: loguniform
    _value: [ 0.0001, 0.1 ]
  num_epochs:
     _type : choice
     _value: [5, 6, 7, 8, 10]
  dropout_keep_prob:
     _type: uniform
     _value: [0.5, 1.0]

trial_command: python model.py
trial_code_directory: .

trial_concurrency: 2
max_trial_number: 10

tuner:
  name: TPE
  class_args:
    optimize_mode: maximize

training_service:
  platform: local
